version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    container_name: sesc-clientes-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
